name: Upload to Nexus
description: This GitHub Action upload given file(s) to pointed Nexus instance

author: CDQ AG
branding:
  icon: 'upload'
  color: 'green'

inputs:
  instance-url:
    description: 'Nexus URL'
    required: true

  username:
    description: 'Nexus Username'
    default: ''

  password:
    description: 'Nexus Password'
    default: ''

  repository:
    description: 'Nexus Repository'
    required: true

  default-destination:
    description: 'Default destination path'
    default: ''

  files:
    description: 'Files to upload'
    required: true

  if-local-file-does-not-exist:
    description: 'What to do if the local file does not exist [fail/warn-and-ignore/silent-ignore]'
    default: 'fail'

runs:
  using: node20
  main: dist/main.js
